name: CI

on:
  push:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup do NodeJS
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2

      -  name: instalação do Mocha para teste
         run: | 
         cd src;
         npm install -g mocha;
         npm install
     
